import type { ClimbChallenge } from './routes';
import profiles from './canal-profiles.json';
const destinations=[
 {id:'canal-pontivy-josselin',name:'Canal de Nantes à Brest · Pontivy → Josselin',subtitle:'Écluses, biefs et vallée de l’Oust',difficulty:2,xp:100,points:3,sourceUrl:'https://www.francevelotourisme.com/itineraire/la-velodyssee-eurovelo-1/pontivy-josselin',scenery:'Depuis Pontivy, le canal offre un fil conducteur entre les biefs et les passages d’écluses. Le relief représenté se détend progressivement vers la vallée de l’Oust. Rohan appartient à cette étape avant l’arrivée à Josselin. Le voyage peut se répartir sur plusieurs séances ; les détours vers les villages et l’abbaye de Timadeuc ne sont pas ajoutés à la trace.',highlights:['Pontivy','Canal de Nantes à Brest','Rohan · sur l’étape','Josselin']},
 {id:'canal-josselin-peillac',name:'Canal de Nantes à Brest · Josselin → Peillac',subtitle:'Un long ruban tranquille au bord de l’eau',difficulty:1,xp:90,points:3,sourceUrl:'https://www.francevelotourisme.com/itineraire/la-velodyssee-eurovelo-1/josselin-peillac',scenery:'La suite du voyage accompagne l’Oust depuis Josselin vers Peillac. Malestroit marque une étape de découverte le long de cet itinéraire aux faibles ondulations. L’ambiance du halage invite à un effort régulier : la difficulté vient surtout de la durée, que le mode Voyage permet de répartir librement. Les visites des rues et les excursions voisines restent hors du profil.',highlights:['Josselin','Vallée de l’Oust','Malestroit · sur l’étape','Peillac']},
 {id:'canal-pontivy-josselin-short',parentRouteId:'canal-pontivy-josselin',name:'Pontivy · premiers biefs',subtitle:'Une courte échappée le long du canal',difficulty:1,xp:40,points:2,sourceUrl:'https://www.francevelotourisme.com/itineraire/la-velodyssee-eurovelo-1/pontivy-josselin',scenery:'Cette portion conserve uniquement les premiers kilomètres de la trace au départ de Pontivy. Quelques ondulations ponctuent le halage avant un arrêt virtuel au bord du canal. Elle ne rejoint ni Rohan ni Josselin et garde sa propre validation.',highlights:['Pontivy','Halage','Portion courte']},
 {id:'canal-josselin-peillac-short',parentRouteId:'canal-josselin-peillac',name:'Josselin · parenthèse au fil de l’eau',subtitle:'Une demi-heure simulée pour s’évader',difficulty:1,xp:40,points:2,sourceUrl:'https://www.francevelotourisme.com/itineraire/la-velodyssee-eurovelo-1/josselin-peillac',scenery:'Au départ de Josselin, cette courte portion suit environ sept kilomètres et demi de halage. Le profil doux convient à un roulage tranquille. L’arrivée est un point d’arrêt virtuel sur le tracé, avant Malestroit ; aucune visite supplémentaire n’est simulée.',highlights:['Josselin','Halage','Portion courte']}
] as const;
export const canalRoutes:ClimbChallenge[]=destinations.map(d=>{
 const data=profiles[d.id];return {...d,...data,highlights:[...d.highlights],coordinates:data.coordinates.map(([lat,lon])=>[lat,lon]),region:'Bretagne · Canal de Nantes à Brest',category:d.difficulty===1?'scenic':'stage',effort:d.difficulty===1?'easy':'moderate',tags:['Bretagne','canal','eau','halage'],sourceLabel:'France Vélo Tourisme · GPX officiel',note:`${data.provenance.section} Profil lissé à 500 m ; dénivelé calculé sur ce profil. Simulation intérieure, sans navigation extérieure. ${'parentRouteId' in d?'La portion courte ne valide pas son étape parent.':'Voyage permet de fractionner cette étape.'}`};
});
export const canalFullRouteIds=['canal-pontivy-josselin','canal-josselin-peillac'];
