/** Plain-language definitions shared by preparation and the guide in Plus. */
export const cyclingGlossary = [
  { title: "Lire un parcours", terms: [
    { label: "D+ · dénivelé positif", description: "La somme de toutes les montées du parcours, en mètres. Ce n’est pas l’altitude du sommet ni la différence entre départ et arrivée.", example: "Tu montes de 100 m, descends de 60 m, puis remontes de 80 m : le D+ est de 180 m." },
    { label: "D− · dénivelé négatif", description: "La somme de toutes les descentes du parcours, en mètres.", example: "Deux descentes de 50 m et 30 m donnent 80 m de D−." },
    { label: "Altitude · hauteur du lieu", description: "La hauteur d’un point du parcours par rapport au niveau de la mer.", example: "Un sommet à 1 000 m d’altitude n’implique pas que tu as grimpé 1 000 m depuis le départ." },
    { label: "Pente · inclinaison en %", description: "Le gain ou la perte de hauteur pour 100 mètres horizontaux. Une valeur positive indique une montée ; une valeur négative, une descente.", example: "Une pente de 5 % monte de 5 m pour 100 m horizontaux." },
    { label: "Profil · dessin du relief", description: "La courbe montre comment l’altitude évolue le long du parcours. Sur vélo d’appartement, ce relief est représenté par des consignes de résistance.", example: "Une bosse sur la courbe correspond à une montée suivie d’une descente." }
  ] },
  { title: "Comprendre tes mesures", terms: [
    { label: "RPM / tr/min · cadence", description: "Le nombre de tours de pédale par minute. RPM vient de l’anglais « revolutions per minute ». Cela décrit ton rythme de pédalage, pas ta vitesse en km/h.", example: "60 RPM = 60 tours par minute, soit un tour de pédale par seconde." },
    { label: "BPM · fréquence cardiaque", description: "Le nombre de battements du cœur par minute, transmis lorsqu’un capteur compatible fournit une mesure. C’est différent de la cadence des jambes.", example: "90 BPM signifie 90 battements en une minute ; ce chiffre seul n’indique pas une intensité à viser." },
    { label: "W / watts · puissance", description: "La puissance de pédalage diffusée par le vélo : elle exprime un effort mécanique par unité de temps. Ce n’est ni un niveau de résistance ni un total de calories.", example: "100 W est une puissance à cet instant ; ce n’est pas 100 kcal dépensées." },
    { label: "km/h · vitesse", description: "Des kilomètres par heure. Sur un vélo d’appartement, la vitesse provient du calcul de la console ; elle ne décrit pas un déplacement réel sur route.", example: "À 20 km/h constants pendant 30 minutes, le compteur correspond à 10 km." },
    { label: "kcal · énergie dépensée", description: "Les kilocalories, souvent appelées simplement « calories ». Le chiffre du vélo est une estimation : sa précision dépend de l’appareil et des informations utilisées.", example: "200 kcal au bilan désigne une énergie estimée sur la séance, pas une puissance instantanée." },
    { label: "RPE · ressenti d’effort", description: "Ta perception de l’effort sur une échelle de 1 à 10 : 1 est très facile, 10 est maximal. La cible guide la séance ; au bilan, tu renseignes ton ressenti réel.", example: "Une cible RPE 3 et un ressenti final de 5 peuvent différer : note ce que tu as vraiment ressenti." },
    { label: "Niveau · résistance", description: "La difficulté de pédalage demandée au vélo. VéloQuest utilise des consignes de 1 à 32 ; leur correspondance avec le vélo dépend de son échelle et des réglages.", example: "Niveau 8 ne veut dire ni 8 km/h ni 8 watts. Ne le confonds pas avec ton niveau de progression dans l’application." }
  ] },
  { title: "Se repérer dans VéloQuest", terms: [
    { label: "XP · points d’expérience", description: "Des points de jeu qui font progresser ton niveau dans VéloQuest. Ils récompensent les séances et objectifs selon les règles de l’application.", example: "Gagner 40 XP n’est pas brûler 40 kcal : progression ludique et mesures physiques sont distinctes." },
    { label: "Segment / secteur", description: "Un segment est une partie de séance avec ses consignes. Un secteur est une portion de parcours utilisée notamment pour un défi chronométré.", example: "L’échauffement peut être le premier segment ; un secteur peut aller du kilomètre 2 au kilomètre 4." },
    { label: "Time Attack / PB / ghost", description: "Time Attack signifie contre-la-montre. PB désigne ton meilleur résultat personnel. Le ghost, ou fantôme, est un repère de comparaison avec une tentative précédente.", example: "Le fantôme sert à comparer ta progression ; ce n’est pas un autre cycliste connecté en direct." },
    { label: "FTMS · connexion au vélo", description: "Un standard Bluetooth pour échanger des données avec des appareils de fitness. Mesures disponibles et pilotage de résistance dépendent des capacités du vélo, du navigateur et des autorisations.", example: "Recevoir la cadence ne garantit pas que l’application peut aussi commander la résistance." },
    { label: "PWA · application web installable", description: "Une application web que tu peux ajouter à l’écran d’accueil si ton navigateur le permet. Son installation ne donne pas automatiquement accès au Bluetooth.", example: "La même application dans deux navigateurs peut avoir deux historiques locaux distincts : utilise l’export/import pour transférer tes données." }
  ] }
] as const;
