import type { ClimbChallenge } from "./routes";
import profiles from "./napoleon-north-profiles.json";

const sections = [
  { id: "napoleon-gap-fare", name: "Route Napoléon · Gap → La Fare", subtitle: "Col Bayard, porte du Champsaur", difficulty: 3, xp: 160, points: 2,
    scenery: "Le bassin de Gap s’éloigne à mesure que la route monte vers le col Bayard. À 1 245 mètres, le passage ouvre le paysage sur le Champsaur et les reliefs qui bordent la vallée du Drac. La descente rejoint La Fare-en-Champsaur, au pied du versant nord. Une vraie ascension suivie d’une récupération, sans détour vers les pistes du plateau. Le départ reprend un point de la trace Michelin dans Gap, distinct de l’arrivée du carnet précédent.", highlights: ["Gap", "Col Bayard · 1 245 m", "Champsaur", "La Fare-en-Champsaur"] },
  { id: "napoleon-fare-corps", name: "Route Napoléon · La Fare → Corps", subtitle: "Du Champsaur aux portes du Beaumont", difficulty: 2, xp: 150, points: 2,
    scenery: "Au nord du col Bayard, la route traverse le Champsaur par Les Barraques, à l’ouest de Saint-Bonnet, puis rejoint le carrefour de Saint-Firmin. Le Valgaudemar s’ouvre vers les hautes montagnes, mais la trace poursuit vers Corps. Les vallons, replats et remontées accompagnent cette transition vers le Beaumont, dominé par la silhouette de l’Obiou. Le lac du Sautet appartient au paysage autour de Corps : aucune descente à ses rives ni montée vers La Salette n’est ajoutée.", highlights: ["La Fare-en-Champsaur", "Les Barraques · Saint-Bonnet", "Saint-Firmin · carrefour", "Corps", "Obiou · paysage"] },
  { id: "napoleon-corps-mure", name: "Route Napoléon · Corps → La Mure", subtitle: "Vallons du Beaumont et plateau matheysin", difficulty: 3, xp: 180, points: 3,
    scenery: "Corps, halte du voyage de mars 1815, ouvre une traversée vallonnée du Beaumont. La route publiée gagne le secteur de La Salle-en-Beaumont, alternant descentes et nouvelles montées avant La Mure. Le plateau matheysin apparaît dans un décor de montagnes et de terres ouvertes, avec la mémoire minière de la ville à l’arrivée. Les paysages du Sautet et de l’Obiou restent ceux des environs ; le Petit Train de La Mure et les passerelles de Monteynard sont des excursions distinctes, absentes du parcours.", highlights: ["Corps", "Beaumont", "La Salle-en-Beaumont · secteur routier", "La Mure", "Matheysine"] },
  { id: "napoleon-mure-laffrey", name: "Route Napoléon · La Mure → Laffrey", subtitle: "Les lacs du plateau et la Rencontre", difficulty: 2, xp: 110, points: 2,
    scenery: "La route quitte La Mure et traverse le plateau matheysin vers le secteur de Pierre-Châtel et Saint-Théoffrey. Les reliefs autour des lacs donnent une ambiance plus ouverte que les vallons du Beaumont. À l’approche de Laffrey, la Prairie de la Rencontre rappelle le 7 mars 1815, lorsque Napoléon retrouva les soldats envoyés pour l’arrêter. Le repère suit la route : le monument, vers le lac, n’est pas une visite simulée. Quelques ondulations ponctuent cette étape, sans tour des lacs ni liaison inventée jusqu’à leurs rives.", highlights: ["La Mure", "Pierre-Châtel · secteur routier", "Saint-Théoffrey", "Prairie de la Rencontre · à proximité", "Laffrey"] },
  { id: "napoleon-laffrey-vizille", name: "Route Napoléon · Laffrey → Vizille", subtitle: "Du plateau à la vallée de la Romanche", difficulty: 2, xp: 70, points: 1,
    scenery: "Depuis Laffrey, le plateau laisse place à une longue descente vers la vallée de la Romanche. Le relief se resserre, puis Vizille apparaît au pied des montagnes. La ville est connue pour son domaine et son château, associés à l’assemblée de 1788 et au musée de la Révolution française. L’arrivée du GPX se situe dans le secteur routier près du pont sur la Romanche : la visite du château reste distincte. Ce court tronçon conserve le relief descendant, avec une résistance manuelle ajustable et aucun objectif de vitesse.", highlights: ["Laffrey", "Descente vers la Romanche", "Vizille", "Domaine de Vizille · dans la ville"] },
  { id: "napoleon-vizille-grenoble", name: "Route Napoléon · Vizille → Grenoble", subtitle: "Brié, Eybens et l’arrivée dauphinoise", difficulty: 3, xp: 140, points: 2,
    scenery: "Le dernier tronçon remonte depuis Vizille vers le secteur de Brié-et-Angonnes, avant de redescendre vers Eybens. Le plateau offre une transition entre la vallée de la Romanche et l’agglomération grenobloise, entourée par les massifs du Vercors, de la Chartreuse et de Belledonne. Eybens marque le retour en ville, puis la trace publiée rejoint Grenoble. Le voyage se termine sur ce point du GPX, sans montée à la Bastille ni détour vers une place historique. La remontée initiale apporte une dernière difficulté avant les kilomètres urbains.", highlights: ["Vizille", "Brié-et-Angonnes · secteur routier", "Eybens", "Grenoble", "Massifs autour de Grenoble"] }
] as const;

// Keep this northern collection separate from the eight previously rewarded stages.
export const napoleonNorthRouteIds: string[] = sections.map((section) => section.id);
export const napoleonNorthRoutes: ClimbChallenge[] = sections.map((section) => {
  const data = profiles[section.id];
  return { ...section, ...data, category: "stage", region: "Alpes · Route Napoléon", tags: ["Route Napoléon", "Alpes", "histoire", "itinérance", ...section.highlights],
    highlights: [...section.highlights], coordinates: data.coordinates.map(([lat, lon]) => [lat, lon]),
    effort: section.difficulty === 2 ? "moderate" : "hard",
    sourceLabel: "Michelin Éditions · Grenoble–Embrun, extrait inversé",
    sourceUrl: "https://editions.michelin.com/la-route-napoleon-1-grenoble-embrun/",
    note: "Une seule trace publiée, découpée et inversée ; altitudes IGN RGE ALTI lissées à 500 m. D+ calculé sur le profil représenté. Les six tronçons partagent leurs extrémités ; le départ à Gap diffère d’environ 260 m de l’arrivée du carnet précédent, sans liaison ajoutée. Résistance manuelle 1–32 et pauses libres. Simulation sur vélo d’intérieur, sans guidage routier réel." };
});
