import type { ClimbChallenge } from "./routes";
import scenicPlaces from "./legacy-route-places.json";

const simplifiedNote = "Repères de découverte indicatifs sur un profil géographique simplifié. Les kilomètres intermédiaires ne sont pas des positions GPS relevées. Progression virtuelle ou distance reçue du vélo.";
const descriptions: Record<string, { scenery: string; highlights: string[]; labels: string[]; sourceUrl?: string }> = {
  "alpe-dhuez": { scenery: "Les 21 virages s’élèvent au-dessus de Bourg-d’Oisans et de la vallée de la Romanche. La Garde marque les premiers lacets, puis les hameaux et Huez accompagnent la montée vers la station. Les paysages de l’Oisans s’ouvrent progressivement sur les reliefs voisins. La pente soutenue invite à trouver un rythme régulier plutôt qu’à accélérer à chaque virage.", highlights: ["Bourg-d’Oisans", "La Garde", "Huez", "Les 21 virages", "Oisans"], labels: ["Bourg-d’Oisans", "La Garde · secteur", "Huez · secteur", "Alpe d’Huez"] },
  "ventoux-bedoin": { scenery: "Depuis Bédoin, les premières routes provençales conduisent vers le secteur de Saint-Estève. La forêt accompagne ensuite la partie longue et soutenue de l’ascension. Au Chalet Reynard, le décor s’ouvre sur les pentes minérales du Géant de Provence. Le sommet et sa silhouette reconnaissable couronnent cette progression du village aux paysages de haute altitude.", highlights: ["Bédoin", "Saint-Estève", "Forêt du Ventoux", "Chalet Reynard", "Sommet du Ventoux"], labels: ["Bédoin", "Saint-Estève · secteur", "Chalet Reynard · secteur", "Mont Ventoux · sommet"] },
  "tourmalet-est": { scenery: "Le versant oriental part du pays de Campan et gagne la vallée de Gripp. Les prairies et les bois cèdent progressivement la place aux pentes de montagne et à La Mongie. Au-dessus de la station, les lacets conduisent au col du Tourmalet, sous les reliefs du Pic du Midi. L’arrivée ouvre les vues vers les vallées de Gripp et du Bastan.", highlights: ["Campan", "Vallée de Gripp", "La Mongie", "Tourmalet", "Pic du Midi · panorama"], labels: ["Campan · départ du profil", "Vallée de Gripp", "La Mongie · secteur", "Col du Tourmalet"] },
  "galibier-valloire": { scenery: "Depuis Valloire, la route remonte vers Bonnenuit puis Plan Lachat. Le paysage devient plus ouvert, entre prairies d’altitude et reliefs rocheux. Au-delà de Plan Lachat, les lacets gagnent un décor de haute montagne jusqu’au Galibier. Ce parcours représente la montée depuis Valloire ; il ne comprend pas l’ascension préalable du Télégraphe.", highlights: ["Valloire", "Bonnenuit", "Plan Lachat", "Col du Galibier", "Haute montagne"], labels: ["Valloire", "Bonnenuit · secteur", "Plan Lachat · secteur", "Col du Galibier"] },
  "madeleine-maurienne": { scenery: "La montée quitte La Chambre et la vallée de la Maurienne pour gagner les pentes de Saint-François-Longchamp. Lacets, passages boisés puis espaces d’alpage accompagnent une ascension longue. Le col de la Madeleine sépare les paysages de la Lauzière et de la Vanoise, avec une ouverture vers la Tarentaise. Le sommet marque ici la fin de la séance, sans descente sur l’autre versant.", highlights: ["La Chambre", "Saint-François-Longchamp", "Alpages", "Lauzière", "Col de la Madeleine"], labels: ["La Chambre", "Saint-François-Longchamp · secteur", "Alpages de la Madeleine", "Col de la Madeleine"] },
  "croix-de-fer-maurienne": { scenery: "Depuis Saint-Jean-de-Maurienne, la montée rejoint les paysages de la vallée de l’Arvan puis le pays des Arves. Saint-Sorlin-d’Arves annonce la partie haute, où les alpages et les silhouettes des Aiguilles d’Arves donnent toute son ampleur au décor. Le col de la Croix-de-Fer conclut cette longue ascension. Le voisin Glandon et le lac de Grand’Maison sont des destinations distinctes.", highlights: ["Saint-Jean-de-Maurienne", "Vallée de l’Arvan", "Saint-Sorlin-d’Arves", "Aiguilles d’Arves", "Croix-de-Fer"], labels: ["Saint-Jean-de-Maurienne", "Vallée de l’Arvan", "Saint-Sorlin-d’Arves · secteur", "Col de la Croix-de-Fer"] },
  "glandon-cuines": { scenery: "La route quitte Saint-Étienne-de-Cuines pour remonter la vallée des Villards. Le secteur de Saint-Colomban-des-Villards apporte un passage plus ouvert avant le retour des fortes pentes. Les derniers lacets gagnent les paysages d’alpage du Glandon. Le final est exigeant malgré les replats précédents ; l’arrivée au col ne comprend pas la liaison vers la Croix-de-Fer.", highlights: ["Saint-Étienne-de-Cuines", "Vallée des Villards", "Saint-Colomban-des-Villards", "Lacets du Glandon"], labels: ["Saint-Étienne-de-Cuines", "Vallée des Villards", "Saint-Colomban-des-Villards · secteur", "Col du Glandon"] },
  "iseran-bonneval": { scenery: "Les maisons de pierre de Bonneval-sur-Arc précèdent les alpages du vallon de la Lenta. La montée passe vers le pont de l’Oulietta puis gagne un paysage de plus en plus minéral dans le parc de la Vanoise. L’Iseran termine cette ascension de haute altitude. La simulation s’arrête au col ; elle ne descend pas vers Val-d’Isère.", highlights: ["Bonneval-sur-Arc", "Vallon de la Lenta", "Pont de l’Oulietta", "Vanoise", "Col de l’Iseran"], labels: ["Bonneval-sur-Arc", "Vallon de la Lenta", "Pont de l’Oulietta · secteur", "Col de l’Iseran"], sourceUrl: "https://www.velo-maurienne.com/equipement/montee-cyclo-du-col-de-liseran-depuis-bonneval-sur-arc-bonneval-sur-arc/" },
  "enclave-papes-loop": { scenery: "La boucle part de Valréas et traverse les paysages viticoles de l’Enclave des Papes. Visan, Richerenches puis Grillon composent les haltes de ce voyage entre vignes, cultures et villages provençaux. Les reliefs des Baronnies et du Ventoux appartiennent à l’horizon. La séance conserve son alternance de bosses, descentes et récupérations ; les visites des monuments restent hors du profil.", highlights: ["Valréas", "Visan", "Richerenches", "Grillon", "Vignes de l’Enclave"], labels: ["Valréas · départ", "Visan · secteur", "Richerenches · secteur", "Grillon · secteur", "Valréas · retour"], sourceUrl: "https://provence-alpes-cotedazur.com/que-faire/itineraires-randonnee/28-tour-de-lenclave-a-velo-valreas-fr-4346718/" },
  "vaison-medieval-loop": { scenery: "Autour de Vaison-la-Romaine, les petites routes du Vaisonnais relient les secteurs de Saint-Romain-en-Viennois, Puyméras, Faucon et Entrechaux, avant le retour vers Vaison. Villages perchés, vignes et vues vers le Ventoux donnent son identité à la boucle. Le Crestet est un détour de découverte possible sur l’itinéraire touristique ; aucune montée supplémentaire au village n’est ajoutée au profil conservé.", highlights: ["Vaison-la-Romaine", "Saint-Romain-en-Viennois", "Puyméras", "Faucon", "Entrechaux", "Ventoux · panorama"], labels: ["Vaison-la-Romaine · départ", "Saint-Romain-en-Viennois · secteur", "Puyméras · secteur", "Faucon · secteur", "Entrechaux · secteur", "Vaison-la-Romaine · retour"], sourceUrl: "https://www.cheminsdesparcs.fr/fr/trek/134087-VAISON-LA-ROMAINE----Les-villages-Medievaux-a-velo" },
  "uchaux-loop": { scenery: "Le tour du massif d’Uchaux retrouve les paysages de la vallée du Rhône depuis Bollène. Les collines boisées et les vignobles rythment une sortie de petites bosses et de faux-plats. Le massif apporte une ambiance plus ombragée que les grands plateaux provençaux, sans ascension de haute montagne. Le retour à Bollène ferme cette boucle, dont les détails intermédiaires restent une représentation d’entraînement simplifiée.", highlights: ["Bollène", "Massif d’Uchaux", "Collines boisées", "Vignobles de la vallée du Rhône"], labels: ["Bollène · départ", "Massif d’Uchaux · secteur boisé", "Bollène · retour"] },
  "sorgue-velleron-loop": { scenery: "Velleron ouvre cette boucle du pays des Sorgues. L’itinéraire touristique relie Pernes-les-Fontaines puis L’Isle-sur-la-Sorgue, avant de retrouver Le Thor et les paysages de vergers. Canaux, villages et campagnes du Comtat accompagnent le voyage. La séance conserve ses faux-plats et ses récupérations : les passages dans les centres historiques sont des repères de découverte, sans visite ajoutée.", highlights: ["Velleron", "Pernes-les-Fontaines", "L’Isle-sur-la-Sorgue", "Le Thor", "Canaux et vergers"], labels: ["Velleron · départ", "Pernes-les-Fontaines · secteur", "L’Isle-sur-la-Sorgue · secteur", "Le Thor · secteur", "Velleron · retour"], sourceUrl: "https://provence-alpes-cotedazur.com/que-faire/itineraires-randonnee/11-du-ventoux-a-lisle-sur-la-sorgue-velleron-fr-4347403/" },
  "nice-corniches-loop": { scenery: "Le départ niçois gagne les paysages de la Riviera par la Basse Corniche, à hauteur d’Èze-sur-Mer, Cap-d’Ail et Monaco. Menton marque le passage vers les reliefs du retour, puis La Turbie et le secteur du col d’Èze ouvrent les vues sur la côte avant Nice. Cette boucle conserve son ancien profil simplifié ; les traces GPX distinctes des deux Corniches offrent des versions plus détaillées.", highlights: ["Nice", "Èze-sur-Mer", "Cap-d’Ail", "Monaco", "Menton", "La Turbie", "Col d’Èze"], labels: ["Nice · départ", "Èze-sur-Mer · secteur", "Monaco · secteur", "Menton · secteur", "La Turbie · secteur", "Col d’Èze · secteur", "Nice · retour"] },
  "chaussy-madeleine-stage": { scenery: "Cette grande boucle de Maurienne associe le Chaussy et la Madeleine, entre villages, versants boisés et alpages. Le passage vers Saint-François-Longchamp précède la partie haute de la Madeleine ; la descente retrouve La Chambre avant le retour vers Saint-Jean-de-Maurienne. Le profil d’entraînement représente l’enchaînement des deux cols, avec une récupération entre les ascensions. Il ne constitue pas un relevé GPS de chaque lacet.", highlights: ["Saint-Jean-de-Maurienne", "Col du Chaussy", "Saint-François-Longchamp", "Col de la Madeleine", "La Chambre"], labels: ["Saint-Jean-de-Maurienne · départ", "Col du Chaussy · secteur", "Saint-François-Longchamp · secteur", "Col de la Madeleine · secteur", "La Chambre · secteur", "Saint-Jean-de-Maurienne · retour"] }
};

export function enrichRouteDescription(route: ClimbChallenge): ClimbChallenge {
  const details = descriptions[route.id];
  if (details) return { ...route, scenery: details.scenery, highlights: details.highlights,
    sourceUrl: details.sourceUrl ?? route.sourceUrl, placesNote: simplifiedNote,
    places: details.labels.map((label, index) => ({ label, landmark: "Repère de découverte · emplacement indicatif sur le profil simplifié.", km: index === details.labels.length-1 ? route.distanceKm : Number((route.distanceKm*index/(details.labels.length-1)).toFixed(3)) })) };
  const places = scenicPlaces[route.id as keyof typeof scenicPlaces];
  return places ? { ...route, places } : route;
}
